import './assets/main.css'

import { createApp } from 'vue'
import App from './App.vue'
import router from './router.ts'

document.cookie = `auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJsb2NhbGUiOiJ6aC1jbiIsInZpZXdNb2RlIjoibW9zYWljIiwic2luZ2xlQ2xpY2siOmZhbHNlLCJwZXJtIjp7ImFkbWluIjp0cnVlLCJleGVjdXRlIjp0cnVlLCJjcmVhdGUiOnRydWUsInJlbmFtZSI6dHJ1ZSwibW9kaWZ5Ijp0cnVlLCJkZWxldGUiOnRydWUsInNoYXJlIjp0cnVlLCJkb3dubG9hZCI6dHJ1ZX0sImNvbW1hbmRzIjpbImJhc2giLCJscyIsInNoIiwid2dldCIsImNobW9kIiwicm0iLCJta2RpciIsInB3ZCJdLCJsb2NrUGFzc3dvcmQiOmZhbHNlLCJoaWRlRG90ZmlsZXMiOmZhbHNlLCJkYXRlRm9ybWF0IjpmYWxzZSwidXNlcm5hbWUiOiJhZG1pbiJ9LCJpc3MiOiJGaWxlIEJyb3dzZXIiLCJleHAiOjE3NTY4OTUyMjYsImlhdCI6MTc1Njg4ODAyNn0.peafDWEB1Ep2qxHFhLj07KGndpk0tb2S3zvqV-m4O3I; path=/; SameSite=Lax`

const app = createApp(App)

app.use(router)

app.mount('#app')
