// <auto-generated />
using System;
using CircleService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CircleService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CircleService.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ACTIVITY_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<int>("CircleId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CIRCLE_ID");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("END_TIME");

                    b.Property<string>("Reward")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REWARD");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("START_TIME");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TITLE");

                    b.HasKey("ActivityId");

                    b.ToTable("ACTIVITIES");
                });

            modelBuilder.Entity("CircleService.Models.ActivityParticipant", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ACTIVITY_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("JoinTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("JOIN_TIME");

                    b.Property<int>("RewardStatus")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REWARD_STATUS");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("ActivityId", "UserId");

                    b.ToTable("ACTIVITY_PARTICIPANTS");
                });

            modelBuilder.Entity("CircleService.Models.Circle", b =>
                {
                    b.Property<int>("CircleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CIRCLE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CircleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<int>("OwnerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("OWNER_ID");

                    b.HasKey("CircleId");

                    b.ToTable("CIRCLES");
                });

            modelBuilder.Entity("CircleService.Models.CircleMember", b =>
                {
                    b.Property<int>("CircleId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CIRCLE_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID")
                        .HasColumnOrder(1);

                    b.Property<int>("Points")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("POINTS");

                    b.Property<int>("Role")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROLE");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("CircleId", "UserId");

                    b.ToTable("CIRCLE_MEMBERS");
                });

            modelBuilder.Entity("CircleService.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NOTIFICATION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IS_READ");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RELATED_ID");

                    b.Property<int?>("SenderId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SENDER_ID");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TYPE");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.HasKey("NotificationId");

                    b.ToTable("NOTIFICATIONS");
                });
#pragma warning restore 612, 618
        }
    }
}
